-- ============================================================
-- GREEN CAMPUS SUSTAINABILITY ANALYTICS PORTAL
-- Complete database recreation script
-- ============================================================

CREATE DATABASE IF NOT EXISTS green_campus
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE green_campus;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS sustainability_reports;
DROP TABLE IF EXISTS sustainability_metrics;
DROP TABLE IF EXISTS consumption_records;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS users;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 1. WEB USERS
-- Used by Register/Login. Passwords are stored as SHA-256 hashes
-- by the Java API, never as plain text.
-- ============================================================

CREATE TABLE users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(100) NOT NULL,
    user_code VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL UNIQUE,
    department VARCHAR(100) NOT NULL,
    campus VARCHAR(100) NOT NULL,
    password_hash CHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. RESOURCES
-- Used by Java standalone CRUD stage.
-- ============================================================

CREATE TABLE resources (
    resource_id INT PRIMARY KEY AUTO_INCREMENT,
    resource_name VARCHAR(100) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 3. CONSUMPTION RECORDS
-- ============================================================

CREATE TABLE consumption_records (
    record_id INT PRIMARY KEY AUTO_INCREMENT,
    resource_id INT NOT NULL,
    consumption_value DECIMAL(12,2) NOT NULL,
    consumption_date DATE NOT NULL,
    campus_location VARCHAR(100) NOT NULL,
    CONSTRAINT fk_consumption_resource
        FOREIGN KEY (resource_id)
        REFERENCES resources(resource_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
-- 4. SUSTAINABILITY METRICS
-- Used by Java standalone CRUD stage and the XML example data.
-- ============================================================

CREATE TABLE sustainability_metrics (
    metric_id INT PRIMARY KEY AUTO_INCREMENT,
    metric_name VARCHAR(100) NOT NULL,
    metric_value DECIMAL(12,2) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    metric_date DATE NOT NULL,
    description VARCHAR(255)
);

-- ============================================================
-- 5. WEB REPORT SUBMISSIONS
-- Keeps the existing report form separate from the Java CRUD
-- sustainability_metrics table, so previous stages are preserved.
-- ============================================================

CREATE TABLE sustainability_reports (
    report_id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    metric_name VARCHAR(100) NOT NULL,
    metric_value DECIMAL(12,2) NOT NULL,
    report_date DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_report_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
-- SAMPLE DATA FOR THE EXISTING JAVA CRUD STAGE
-- IDs are explicit so the database is immediately usable.
-- ============================================================

INSERT INTO resources
    (resource_id, resource_name, resource_type, unit, description)
VALUES
    (1, 'Solar Energy', 'Renewable Energy', 'kWh',
     'Electricity generated from campus solar panels'),
    (2, 'Wind Energy', 'Renewable Energy', 'kWh',
     'Electricity generated by campus wind turbines'),
    (3, 'Water', 'Natural Resource', 'Litres',
     'Water consumed across the campus'),
    (4, 'LED Lighting', 'Energy Efficiency', 'kWh',
     'Electricity usage of energy-efficient LED lighting');

INSERT INTO consumption_records
    (record_id, resource_id, consumption_value, consumption_date, campus_location)
VALUES
    (1, 1, 125.50, '2026-09-07', 'Main Campus'),
    (2, 2, 87.25, '2026-09-08', 'Engineering Campus'),
    (3, 3, 2500.00, '2026-09-09', 'Main Campus');

INSERT INTO sustainability_metrics
    (metric_id, metric_name, metric_value, unit, metric_date, description)
VALUES
    (1, 'Solar Energy Generation', 85.75, 'kWh', '2026-09-07',
     'Daily solar energy generated on campus'),
    (2, 'Carbon Emission Reduction', 42.30, 'kg CO2', '2026-09-08',
     'Estimated carbon emissions avoided through renewable energy'),
    (3, 'Water Conservation', 18.50, 'Percent', '2026-09-09',
     'Percentage of water saved through conservation practices');

ALTER TABLE resources AUTO_INCREMENT = 5;
ALTER TABLE consumption_records AUTO_INCREMENT = 4;
ALTER TABLE sustainability_metrics AUTO_INCREMENT = 4;

-- Verify the recreated database.
SHOW TABLES;

SELECT * FROM users;
SELECT * FROM resources;
SELECT * FROM consumption_records;
SELECT * FROM sustainability_metrics;
SELECT * FROM sustainability_reports;
